# Some of these values are overridden when running with docker compose

spring:
  application:
    name: meli-apc-back
  datasource:
    url: jdbc:postgresql://localhost:5432/apc
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

app:
  base-url: http://localhost:${server.port}
  meli:
    base-url: https://api.mercadolibre.com/sites/${MELI_SITE_ID}
    access-token: ${MELI_ACCESS_TOKEN}