spring:
    application:
        name: meli-apc-back

server:
    port: ${APP_SERVER_PORT:8080}

app:
    base-url: ${APP_BASE_URL}:${server.port}
    meli:
        base-url: https://api.mercadolibre.com/sites/${MELI_SITE_ID}
        access-token: ${MELI_ACCESS_TOKEN}